[package]
name = "mycv"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "1.0.0"
askama = "0.15.4"

tokio = { version = "1", features = ["full"] }
axum = "0.8.8"
